import { 
  Type, 
  Square, 
  Image, 
  Search, 
  MousePointer, 
  Navigation,
  Hash,
  AlignLeft,
  Play,
  Zap,
  Minus,
  Box,
  Star,
  Users,
  DollarSign,
  MapPin,
  Share2,
  List,
  Table,
  BarChart3,
  Clock,
  ChevronDown,
  AlertCircle,
  ChevronRight,
  ChevronLeft,
  HelpCircle,
  Settings,
  Grid,
  Layout,
  FileText,
  Map,
  Tag,
  Menu,
  GitBranch,
  Workflow
} from 'lucide-react';
import { Tool } from '@/types';

export const tools: Tool[] = [
  // Basic Tools
  {
    id: 'select',
    name: 'Select',
    icon: 'MousePointer',
    type: 'text',
    category: 'basic',
    description: 'Select and move elements',
    keywords: ['select', 'move', 'cursor', 'pointer'],
  },
  {
    id: 'text',
    name: 'Text',
    icon: 'Type',
    type: 'text',
    category: 'basic',
    description: 'Add text content',
    keywords: ['text', 'content', 'words', 'paragraph'],
    defaultStyles: {
      fontSize: 16,
      fontFamily: 'inherit',
      color: '#000000',
      backgroundColor: 'transparent',
    },
  },
  {
    id: 'heading',
    name: 'Heading',
    icon: 'Heading1',
    type: 'heading',
    category: 'content',
    description: 'Add heading text',
    keywords: ['heading', 'title', 'h1', 'h2', 'h3'],
    defaultStyles: {
      fontSize: 32,
      fontFamily: 'inherit',
      fontWeight: 'bold',
      color: '#000000',
      backgroundColor: 'transparent',
    },
    defaultContent: {
      text: 'Design better landing pages',
      level: 2,
    },
    defaultProps: {
      headingLevel: 2,
      typography: {
        mobile: { fontSize: 28, lineHeight: 34 },
        tablet: { fontSize: 32, lineHeight: 38 },
        desktop: { fontSize: 40, lineHeight: 46 },
      },
    },
  },
  {
    id: 'paragraph',
    name: 'Paragraph',
    icon: 'AlignLeft',
    type: 'paragraph',
    category: 'content',
    description: 'Add paragraph text',
    keywords: ['paragraph', 'text', 'content', 'body'],
    defaultStyles: {
      fontSize: 16,
      fontFamily: 'inherit',
      color: '#000000',
      backgroundColor: 'transparent',
      lineHeight: 1.5,
    },
    defaultContent: {
      text: 'Use WebBuilder to design, iterate, and publish high-converting landing pages without touching code.',
      variant: 'body',
    },
    defaultProps: {
      paragraphVariant: 'body',
      typography: {
        mobile: { fontSize: 15, lineHeight: 24 },
        tablet: { fontSize: 16, lineHeight: 26 },
        desktop: { fontSize: 18, lineHeight: 28 },
      },
    },
  },
  {
    id: 'button',
    name: 'Button',
    icon: 'Square',
    type: 'button',
    category: 'basic',
    description: 'Add clickable button',
    keywords: ['button', 'click', 'action', 'cta'],
    defaultStyles: {
      fontSize: 16,
      fontFamily: 'inherit',
      fontWeight: '500',
      color: '#ffffff',
      backgroundColor: '#3b82f6',
      borderRadius: 6,
      padding: 12,
      textAlign: 'center',
    },
  },
  {
    id: 'image',
    name: 'Image',
    icon: 'Image',
    type: 'image',
    category: 'media',
    description: 'Add image content',
    keywords: ['image', 'photo', 'picture', 'media'],
    defaultStyles: {
      backgroundColor: '#f3f4f6',
      borderRadius: 4,
    },
    constraints: {
      minWidth: 50,
      minHeight: 50,
    },
  },
  {
    id: 'video',
    name: 'Video',
    icon: 'Play',
    type: 'video',
    category: 'media',
    description: 'Add video content',
    keywords: ['video', 'media', 'player', 'youtube'],
    defaultStyles: {
      backgroundColor: '#000000',
      borderRadius: 4,
    },
    constraints: {
      minWidth: 200,
      minHeight: 150,
    },
  },
  {
    id: 'icon',
    name: 'Icon',
    icon: 'Zap',
    type: 'icon',
    category: 'content',
    description: 'Add icon element',
    keywords: ['icon', 'symbol', 'graphic', 'emoji'],
    defaultStyles: {
      fontSize: 24,
      color: '#1d4ed8',
      backgroundColor: 'transparent',
    },
    defaultProps: {
      iconName: 'star',
      iconBackground: 'none',
      iconPadding: 16,
      iconBackgroundColor: '#eef2ff',
    },
    constraints: {
      minWidth: 24,
      minHeight: 24,
    },
  },

  // Layout Tools
  {
    id: 'container',
    name: 'Container',
    icon: 'Box',
    type: 'container',
    category: 'layout',
    description: 'Add container for grouping elements',
    keywords: ['container', 'div', 'wrapper', 'group'],
    defaultStyles: {
      backgroundColor: 'transparent',
      border: '1px dashed #d1d5db',
      borderRadius: 4,
      padding: 16,
    },
  },
  {
    id: 'spacer',
    name: 'Spacer',
    icon: 'Minus',
    type: 'spacer',
    category: 'layout',
    description: 'Add spacing between elements',
    keywords: ['spacer', 'space', 'margin', 'padding'],
    defaultStyles: {
      backgroundColor: '#f3f4f6',
      border: '1px dashed #d1d5db',
    },
    constraints: {
      minWidth: 20,
      minHeight: 20,
    },
  },
  {
    id: 'divider',
    name: 'Divider',
    icon: 'Minus',
    type: 'divider',
    category: 'layout',
    description: 'Add horizontal divider line',
    keywords: ['divider', 'line', 'separator', 'hr'],
    defaultStyles: {
      backgroundColor: '#d1d5db',
      height: 1,
    },
    constraints: {
      minHeight: 1,
      maxHeight: 10,
    },
  },

  // Navigation Tools
  {
    id: 'navbar',
    name: 'Navbar',
    icon: 'Navigation',
    type: 'navbar',
    category: 'navigation',
    description: 'Add navigation bar',
    keywords: ['navbar', 'navigation', 'menu', 'header'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      padding: 16,
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
  },
  {
    id: 'menu',
    name: 'Menu',
    icon: 'Menu',
    type: 'menu',
    category: 'navigation',
    description: 'Add dropdown menu',
    keywords: ['menu', 'dropdown', 'navigation', 'list'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 6,
      padding: 8,
    },
  },
  {
    id: 'breadcrumb',
    name: 'Breadcrumb',
    icon: 'ChevronRight',
    type: 'breadcrumb',
    category: 'navigation',
    description: 'Add breadcrumb navigation',
    keywords: ['breadcrumb', 'navigation', 'path', 'trail'],
    defaultStyles: {
      backgroundColor: 'transparent',
      fontSize: 14,
      color: '#6b7280',
    },
  },

  // Content Tools
  {
    id: 'card',
    name: 'Card',
    icon: 'Square',
    type: 'card',
    category: 'content',
    description: 'Add card component',
    keywords: ['card', 'panel', 'container', 'box'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
      padding: 24,
      boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    },
    defaultContent: {
      eyebrow: 'Featured template',
      title: 'Launch stunning pages in minutes',
      description: 'Use WebBuilder to design, iterate, and publish high-converting landing pages without touching code.',
      image: {
        url: 'https://images.unsplash.com/photo-1523475472560-d2df97ec485c?auto=format&fit=crop&w=960&q=80',
        alt: 'Web design workspace',
      },
      primaryAction: {
        label: 'Start building',
        href: '#',
      },
      secondaryAction: {
        label: 'View docs',
        href: '#',
      },
      features: [
        {
          id: 'feature-1',
          label: 'Visual editing',
          description: 'Drag & drop sections, use keyboard shortcuts, and preview responsive breakpoints.',
        },
        {
          id: 'feature-2',
          label: 'One-click export',
          description: 'Download production-ready HTML/CSS or sync with your repo instantly.',
        },
      ],
    },
    defaultProps: {
      cardLayout: 'image-top',
      cardHighlight: false,
      cardAccentColor: '#2563eb',
    },
  },
  {
    id: 'hero',
    name: 'Hero',
    icon: 'Star',
    type: 'hero',
    category: 'content',
    description: 'Add hero section',
    keywords: ['hero', 'banner', 'header', 'intro'],
    defaultStyles: {
      backgroundColor: '#f8fafc',
      padding: 64,
      textAlign: 'center',
    },
    defaultContent: {
      title: 'Welcome to Our Website',
      subtitle: 'Create amazing experiences with our powerful tools and features.',
      backgroundImage: '',
      buttons: [
        { text: 'Get Started', primary: true },
        { text: 'Learn More', primary: false }
      ]
    },
  },
  {
    id: 'testimonial',
    name: 'Testimonial',
    icon: 'Users',
    type: 'testimonial',
    category: 'content',
    description: 'Add testimonial section',
    keywords: ['testimonial', 'review', 'quote', 'feedback'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
      padding: 24,
    },
    defaultContent: {
      quote: 'This product has completely transformed how we work. The results speak for themselves.',
      name: 'Sarah Johnson',
      role: 'Marketing Director',
      company: 'TechCorp',
      avatar: ''
    },
  },
  {
    id: 'pricing',
    name: 'Pricing',
    icon: 'DollarSign',
    type: 'pricing',
    category: 'ecommerce',
    description: 'Add pricing table',
    keywords: ['pricing', 'price', 'cost', 'plan'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
      padding: 24,
    },
    defaultContent: {
      name: 'Pro Plan',
      description: 'Perfect for growing businesses',
      price: '$29',
      period: 'month',
      features: [
        'Unlimited projects',
        '24/7 support',
        'Advanced analytics',
        'Custom integrations'
      ],
      buttonText: 'Get Started',
      featured: false
    },
  },
  {
    id: 'contact',
    name: 'Contact',
    icon: 'MapPin',
    type: 'contact',
    category: 'forms',
    description: 'Add contact form',
    keywords: ['contact', 'form', 'email', 'message'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
      padding: 24,
    },
    defaultContent: {
      title: 'Get in Touch',
      description: 'We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
      contactInfo: [
        { text: '123 Main St, City, State 12345' },
        { text: 'hello@example.com' },
        { text: '+1 (555) 123-4567' }
      ]
    },
  },
  {
    id: 'map',
    name: 'Map',
    icon: 'Map',
    type: 'map',
    category: 'content',
    description: 'Add map component',
    keywords: ['map', 'location', 'address', 'directions'],
    defaultStyles: {
      backgroundColor: '#f3f4f6',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
    },
  },
  {
    id: 'social',
    name: 'Social',
    icon: 'Share2',
    type: 'social',
    category: 'social',
    description: 'Add social media links',
    keywords: ['social', 'media', 'share', 'follow'],
    defaultStyles: {
      backgroundColor: 'transparent',
      display: 'flex',
      gap: 8,
    },
  },

  // Form Tools
  {
    id: 'form',
    name: 'Form',
    icon: 'FileText',
    type: 'form',
    category: 'forms',
    description: 'Add form container',
    keywords: ['form', 'input', 'submit', 'contact'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
      padding: 24,
    },
  },
  {
    id: 'search',
    name: 'Search',
    icon: 'Search',
    type: 'search',
    category: 'forms',
    description: 'Add search input',
    keywords: ['search', 'input', 'find', 'query'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #d1d5db',
      borderRadius: 6,
      padding: 8,
      fontSize: 16,
    },
  },

  // Advanced Tools
  {
    id: 'gallery',
    name: 'Gallery',
    icon: 'Grid3X3',
    type: 'gallery',
    category: 'media',
    description: 'Add image gallery',
    keywords: ['gallery', 'images', 'photos', 'grid'],
    defaultStyles: {
      backgroundColor: '#f3f4f6',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
      padding: 16,
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
      gap: 16,
    },
  },
  {
    id: 'carousel',
    name: 'Carousel',
    icon: 'ChevronLeft',
    type: 'carousel',
    category: 'media',
    description: 'Add image carousel',
    keywords: ['carousel', 'slider', 'images', 'slideshow'],
    defaultStyles: {
      backgroundColor: '#f3f4f6',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
      overflow: 'hidden',
    },
  },
  {
    id: 'tabs',
    name: 'Tabs',
    icon: 'Square',
    type: 'tabs',
    category: 'content',
    description: 'Add tabbed content',
    keywords: ['tabs', 'navigation', 'content', 'sections'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
    },
  },
  {
    id: 'accordion',
    name: 'Accordion',
    icon: 'ChevronDown',
    type: 'accordion',
    category: 'content',
    description: 'Add accordion component',
    keywords: ['accordion', 'collapsible', 'expand', 'faq'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
    },
    defaultContent: {
      heading: 'Frequently Asked Questions',
      subheading: 'Support',
      description: 'Answers to top questions from teams designing with WebBuilder.',
      allowMultiple: false,
      defaultOpenIds: ['accordion-item-1'],
      items: [
        {
          id: 'accordion-item-1',
          title: 'How does WebBuilder work?',
          description: 'Start with a section, customize it visually, and export responsive code.',
          content:
            'Pick a template, drag in elements, then fine-tune spacing, colors, and typography. Everything stays responsive, so you can preview desktop, tablet, and mobile in real time.',
        },
        {
          id: 'accordion-item-2',
          title: 'Can I export the code?',
          description: 'Yes—download a clean HTML/CSS package anytime.',
          content:
            'Generate production-ready markup that mirrors your canvas. Hand it to developers, host it yourself, or iterate further inside your framework of choice.',
        },
        {
          id: 'accordion-item-3',
          title: 'Does it support collaboration?',
          description: 'Share projects, reuse saved sections, and keep brand tokens in sync.',
          content:
            'Save reusable blocks, apply global typography and color tokens, and invite teammates to keep everything on-brand as you ship new pages faster.',
        },
      ],
    },
  },
  {
    id: 'modal',
    name: 'Modal',
    icon: 'Square',
    type: 'modal',
    category: 'content',
    description: 'Add modal dialog',
    keywords: ['modal', 'dialog', 'popup', 'overlay'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
      padding: 24,
      boxShadow: '0 10px 15px rgba(0, 0, 0, 0.1)',
    },
  },
  {
    id: 'tooltip',
    name: 'Tooltip',
    icon: 'HelpCircle',
    type: 'tooltip',
    category: 'content',
    description: 'Add tooltip component',
    keywords: ['tooltip', 'hint', 'help', 'info'],
    defaultStyles: {
      backgroundColor: '#1f2937',
      color: '#ffffff',
      borderRadius: 4,
      padding: 8,
      fontSize: 12,
    },
  },
  {
    id: 'progress',
    name: 'Progress',
    icon: 'BarChart3',
    type: 'progress',
    category: 'content',
    description: 'Add progress bar',
    keywords: ['progress', 'bar', 'loading', 'completion'],
    defaultStyles: {
      backgroundColor: '#e5e7eb',
      borderRadius: 4,
      height: 8,
    },
  },
  {
    id: 'badge',
    name: 'Badge',
    icon: 'Tag',
    type: 'badge',
    category: 'content',
    description: 'Add badge component',
    keywords: ['badge', 'tag', 'label', 'status'],
    defaultStyles: {
      backgroundColor: '#3b82f6',
      color: '#ffffff',
      borderRadius: 12,
      padding: '4px 8px',
      fontSize: 12,
      fontWeight: '500',
    },
  },
  {
    id: 'alert',
    name: 'Alert',
    icon: 'AlertCircle',
    type: 'alert',
    category: 'content',
    description: 'Add alert message',
    keywords: ['alert', 'message', 'notification', 'warning'],
    defaultStyles: {
      backgroundColor: '#fef3c7',
      border: '1px solid #f59e0b',
      color: '#92400e',
      borderRadius: 6,
      padding: 12,
    },
  },
  {
    id: 'list',
    name: 'List',
    icon: 'List',
    type: 'list',
    category: 'content',
    description: 'Add list component',
    keywords: ['list', 'items', 'bullet', 'ordered'],
    defaultStyles: {
      backgroundColor: 'transparent',
      padding: 16,
    },
  },
  {
    id: 'table',
    name: 'Table',
    icon: 'Table',
    type: 'table',
    category: 'content',
    description: 'Add data table',
    keywords: ['table', 'data', 'rows', 'columns'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
      overflow: 'hidden',
    },
  },
  {
    id: 'chart',
    name: 'Chart',
    icon: 'BarChart3',
    type: 'chart',
    category: 'content',
    description: 'Add chart component',
    keywords: ['chart', 'graph', 'data', 'visualization'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
      padding: 16,
    },
  },
  {
    id: 'timeline',
    name: 'Timeline',
    icon: 'Clock',
    type: 'timeline',
    category: 'content',
    description: 'Add timeline component',
    keywords: ['timeline', 'events', 'history', 'chronology'],
    defaultStyles: {
      backgroundColor: 'transparent',
      padding: 16,
    },
  },
  {
    id: 'flowchart',
    name: 'Flowchart',
    icon: 'Workflow',
    type: 'flowchart',
    category: 'content',
    description: 'Add interactive flowchart builder',
    keywords: ['flowchart', 'diagram', 'process', 'workflow', 'chart'],
    defaultStyles: {
      backgroundColor: '#ffffff',
      border: '1px solid #e5e7eb',
      borderRadius: 8,
      padding: 16,
      minHeight: 300,
    },
    constraints: {
      minWidth: 300,
      minHeight: 200,
    },
  },
];

export const toolCategories = [
  { id: 'basic', name: 'Basic', icon: 'Square' },
  { id: 'layout', name: 'Layout', icon: 'Layout' },
  { id: 'content', name: 'Content', icon: 'FileText' },
  { id: 'media', name: 'Media', icon: 'Image' },
  { id: 'forms', name: 'Forms', icon: 'FileText' },
  { id: 'navigation', name: 'Navigation', icon: 'Navigation' },
  { id: 'social', name: 'Social', icon: 'Share2' },
  { id: 'ecommerce', name: 'E-commerce', icon: 'DollarSign' },
  { id: 'advanced', name: 'Advanced', icon: 'Settings' },
];

export const getToolsByCategory = (category: string) => {
  return tools.filter(tool => tool.category === category);
};

export const getToolById = (id: string) => {
  return tools.find(tool => tool.id === id);
};

export const searchTools = (query: string) => {
  const lowercaseQuery = query.toLowerCase();
  return tools.filter(tool => 
    tool.name.toLowerCase().includes(lowercaseQuery) ||
    tool.description?.toLowerCase().includes(lowercaseQuery) ||
    tool.keywords?.some(keyword => keyword.toLowerCase().includes(lowercaseQuery))
  );
};
